# Generated by Django 4.2.13 on 2025-04-29 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("box", "box"), ("item", "item")], max_length=5)),
                ("money", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("preparing", "preparing"), ("shipped", "shipped"), ("delivered", "delivered")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address_customer", models.CharField(blank=True, max_length=100, null=True)),
                ("address_fumio", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("money", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("preparing", "preparing"), ("shipped", "shipped"), ("delivered", "delivered")],
                        max_length=10,
                    ),
                ),
                ("address_customer", models.CharField(blank=True, max_length=100, null=True)),
                ("address_fumio", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stylist_type",
                    models.CharField(
                        blank=True,
                        choices=[("everyone", "Everyone"), ("following", "Following"), ("private", "Private")],
                        default="everyone",
                        max_length=25,
                        null=True,
                    ),
                ),
                ("occasion", models.CharField(blank=True, max_length=100, null=True)),
                ("condition", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("notpaid", "notpaid"), ("open", "open"), ("closed", "closed"), ("boxed", "boxed")],
                        default="notpaid",
                        max_length=10,
                    ),
                ),
                (
                    "boxcuratedby",
                    models.CharField(
                        choices=[
                            ("human_stylist", "human stylist"),
                            ("personalized_algorithm", "personalized algorithm"),
                        ],
                        default="human_stylist",
                        max_length=30,
                    ),
                ),
                (
                    "asktype",
                    models.CharField(choices=[("outfit", "outfit"), ("box", "box")], default="outfit", max_length=30),
                ),
                (
                    "catalogue",
                    models.CharField(
                        choices=[("all_items", "all items"), ("liked_only", "liked only")],
                        default="all_items",
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "creator_profile_visibility",
                    models.CharField(
                        blank=True,
                        choices=[("show", "Show"), ("hide", "Hide")],
                        default="show",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "size_top_xyz",
                    models.CharField(
                        blank=True,
                        choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "size_bottom_xyz",
                    models.CharField(
                        blank=True,
                        choices=[("XS", "XS"), ("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "size_waist_inches",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                            ("31", "31"),
                            ("32", "32"),
                            ("33", "33"),
                            ("34", "34"),
                            ("35", "35"),
                            ("36", "36"),
                            ("37", "37"),
                            ("38", "38"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "size_shoe_eu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("34", "34"),
                            ("35", "35"),
                            ("36", "36"),
                            ("37", "37"),
                            ("38", "38"),
                            ("39", "39"),
                            ("40", "40"),
                            ("41", "41"),
                            ("42", "42"),
                            ("43", "43"),
                            ("44", "44"),
                            ("45", "45"),
                            ("46", "46"),
                            ("47", "47"),
                            ("48", "48"),
                            ("34.5", "34.5"),
                            ("35.5", "35.5"),
                            ("36.5", "36.5"),
                            ("37.5", "37.5"),
                            ("38.5", "38.5"),
                            ("39.5", "39.5"),
                            ("40.5", "40.5"),
                            ("41.5", "41.5"),
                            ("42.5", "42.5"),
                            ("43.5", "43.5"),
                            ("44.5", "44.5"),
                            ("45.5", "45.5"),
                            ("46.5", "46.5"),
                            ("47.5", "47.5"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "size_shoe_uk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("2.5", "2.5"),
                            ("3.5", "3.5"),
                            ("4.5", "4.5"),
                            ("5.5", "5.5"),
                            ("6.5", "6.5"),
                            ("7.5", "7.5"),
                            ("8.5", "8.5"),
                            ("9.5", "9.5"),
                            ("10.5", "10.5"),
                            ("11.5", "11.5"),
                            ("12.5", "12.5"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("maximum_outfits", models.IntegerField(default=5)),
                ("current_outfits", models.IntegerField(default=0)),
                (
                    "creator_id",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
