# Generated by Django 4.2.13 on 2025-04-29 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0001_initial"),
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="outfit1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_outfit1",
                to="core.outfit",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="outfit2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticket_outfit2",
                to="core.outfit",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="outfits_all",
            field=models.ManyToManyField(blank=True, to="core.outfit"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="private_stylist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_stylist_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="style1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="style1_tickets",
                to="studio.style",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="style2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="style2_tickets",
                to="studio.style",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="stylists_all",
            field=models.ManyToManyField(blank=True, related_name="stylist_tickets", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="return",
            name="order_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="box.order"
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="returner_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="creator_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="studio.item"),
        ),
        migrations.AddField(
            model_name="order",
            name="ticket_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="box.ticket"
            ),
        ),
    ]
