# Generated by Django 4.2.13 on 2025-04-29 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("box", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EcommerceStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("shop_url", models.CharField(blank=True, max_length=255, null=True)),
                ("address_street_1", models.CharField(blank=True, max_length=255, null=True)),
                ("address_street_2", models.CharField(blank=True, max_length=255, null=True)),
                ("address_postal_code", models.CharField(blank=True, max_length=50, null=True)),
                ("address_city", models.CharField(blank=True, max_length=50, null=True)),
                ("address_country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("shopify", "Shopify"),
                            ("bigcommerce", "BigCommerce"),
                            ("woocommerce", "WooCommerce"),
                            ("magento", "Magento"),
                            ("squarespace", "Squarespace"),
                            ("wix", "Wix"),
                            ("prestashop", "prestashop"),
                            ("weebly", "weebly"),
                            ("bigcartel", "BIGCARTER"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("api_store_id", models.CharField(blank=True, max_length=255, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("api_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("api_access_token", models.CharField(blank=True, max_length=255, null=True)),
                ("size_mapping", jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SizeCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("one_size", "One Size"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SizeShoeEuCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("34", "34"),
                            ("34.5", "34.5"),
                            ("35", "35"),
                            ("35.5", "35.5"),
                            ("36", "36"),
                            ("36.5", "36.5"),
                            ("37", "37"),
                            ("37.5", "37.5"),
                            ("38", "38"),
                            ("38.5", "38.5"),
                            ("39", "39"),
                            ("39.5", "39.5"),
                            ("40", "40"),
                            ("40.5", "40.5"),
                            ("41", "41"),
                            ("41.5", "41.5"),
                            ("42", "42"),
                            ("42.5", "42.5"),
                            ("43", "43"),
                            ("43.5", "43.5"),
                            ("44", "44"),
                            ("44.5", "44.5"),
                            ("45", "45"),
                            ("45.5", "45.5"),
                            ("46", "46"),
                            ("46.5", "46.5"),
                            ("47", "47"),
                            ("47.5", "47.5"),
                            ("48", "48"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SizeShoeUkCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("2", "2"),
                            ("2.5", "2.5"),
                            ("3", "3"),
                            ("3.5", "3.5"),
                            ("4", "4"),
                            ("4.5", "4.5"),
                            ("5", "5"),
                            ("5.5", "5.5"),
                            ("6", "6"),
                            ("6.5", "6.5"),
                            ("7", "7"),
                            ("7.5", "7.5"),
                            ("8", "8"),
                            ("8.5", "8.5"),
                            ("9", "9"),
                            ("9.5", "9.5"),
                            ("10", "10"),
                            ("10.5", "10.5"),
                            ("11", "11"),
                            ("11.5", "11.5"),
                            ("12", "12"),
                            ("12.5", "12.5"),
                            ("13", "13"),
                            ("13.5", "13.5"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SizeWaistInchCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                            ("31", "31"),
                            ("32", "32"),
                            ("33", "33"),
                            ("34", "34"),
                            ("35", "35"),
                            ("36", "36"),
                            ("37", "37"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("style_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag_name", models.CharField(blank=True, max_length=100)),
                ("tag_type", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StudioOutfitTemp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "item1img",
                    models.ImageField(default="studiooutfittemps/default_img1.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item1id", models.CharField(blank=True, max_length=20)),
                (
                    "item2img",
                    models.ImageField(default="studiooutfittemps/default_img2.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item2id", models.CharField(blank=True, max_length=20)),
                (
                    "item3img",
                    models.ImageField(default="studiooutfittemps/default_img3.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item3id", models.CharField(blank=True, max_length=20)),
                (
                    "item4img",
                    models.ImageField(default="studiooutfittemps/default_img4.jpg", upload_to="studiooutfittemps/"),
                ),
                ("item4id", models.CharField(blank=True, max_length=20)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="box.ticket"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("ecommerce_product_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("top", "top"),
                            ("bottom", "bottom"),
                            ("accessory", "accessory"),
                            ("footwear", "footwear"),
                            ("dress", "dress"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        blank=True, choices=[("physical", "physical"), ("virtual", "virtual")], max_length=20
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True, choices=[("new", "new"), ("pre-owned", "pre-owned")], max_length=10, null=True
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                ("itemid", models.CharField(blank=True, max_length=30, null=True)),
                ("image", models.ImageField(blank=True, default="items/default.jpg", null=True, upload_to="items/")),
                (
                    "ecommerce_store",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="studio.ecommercestore"
                    ),
                ),
                ("sizes_shoe_eu", models.ManyToManyField(blank=True, to="studio.sizeshoeeucategory")),
                ("sizes_shoe_uk", models.ManyToManyField(blank=True, to="studio.sizeshoeukcategory")),
                ("sizes_waist_inches", models.ManyToManyField(blank=True, to="studio.sizewaistinchcategory")),
                ("sizes_xyz", models.ManyToManyField(blank=True, to="studio.sizecategory")),
                ("taglist", models.ManyToManyField(blank=True, to="studio.tag")),
            ],
        ),
    ]
