# Generated by Django 4.2.13 on 2024-09-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0037_alter_sizecategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ecommercestore",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shopify", "Shopify"),
                    ("bigcommerce", "BigCommerce"),
                    ("woocommerce", "WooCommerce"),
                    ("magento", "Magento"),
                    ("squarespace", "Squarespace"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
